### ISSUE TITLE
2018 tax tables

### ISSUE THREAD

**Issue by joelebeau** [taxee/taxee-tax-statistics#9]
We're just into 2018, and the updated tables for the year aren't in yet. Is this actively being worked on, or are y'all looking for PRs?

**Comment by jdevince** [comment]
I second this question

**Comment by taxee** [comment]
@joelebeau / @jdevince - Thanks for using Taxee.  With all of the changes happening around income taxes, it took a little longer to finalize the changes to the API for the 2018 tax year.

These updates are have been made in this repo, and are available in the latest version of the package published on NPM.
